### ISSUE TITLE
Direct templates such as tags.html not included in sitemap

### ISSUE THREAD

**Issue by VorpalBlade** [dArignac/pelican-extended-sitemap#11]
Direct templates (apart from index.html) are not included in the site map, which I thought was the main differentiator compared to the sitemap plugin in "pelican-plugins" (overview pages).

I have tested both with and without `*_SAVE_AS` (as I normally use `TAGS_SAVE_AS = "tags/index.html"` etc), and I cannot get it to work.

The non-direct-template pages, such as /tag/foo/ are included in the sitemap.

Software versions:
* pelican-extended-sitemap 1.0.5 (from PyPI)
* Pelican 4.0.1 (from PyPI)

**Comment by dArignac** [comment]
Hi @VorpalBlade ,

thanks for the report.

I currently only grab the index page from `DIRECT_TEMPLATES` to be included. Additionally I process the category, author and tag pages.

I'll handle this as feature request to include any direct pages into the sitemap.

**Comment by dArignac** [comment]
Hi @VorpalBlade,

the feature is implemented in 1.2.0: https://pypi.org/project/pelican-extended-sitemap/1.2.0/
