### ISSUE TITLE
Direct templates such as tags.html ignore the SAVE_AS url

### ISSUE THREAD

**Issue by VorpalBlade** [dArignac/pelican-extended-sitemap#14]
I use:
```python
ARCHIVES_SAVE_AS = 'archives/index.html'
CATEGORIES_SAVE_AS = 'categories/index.html'
TAGS_SAVE_AS = 'tags/index.html'
```
in my pelican config to get nicer URLs. (e.g. /tags/).

The generated site maps appears to link to default page tags.html and so on always.

For direct templates there isn't any *_URL variables from what I can tell that you could use though. Not sure how to solve this.

**Comment by dArignac** [comment]
Thanks again for reporting! I fixed this in version 1.2.1: https://pypi.org/project/pelican-extended-sitemap/1.2.1/

**Comment by VorpalBlade** [comment]
Hm, this almost works as I want. It generates entries like `<loc>/archives/index.html</loc>`, when preferably it would be `<loc>/archives/</loc>`. But since there is no URL variables for these, I guess there is no good way to get the site owners preferred URL for direct templates?

**Comment by dArignac** [comment]
Understood. Can you have a look at #15 ? Do you specify the `*_URL` settings for the direct templates, e.g. `ARCHIVES_URL` ?

**Comment by VorpalBlade** [comment]
Adding _URL variables would neatly solve the problem. You could just check if they exist and if so use them (otherwise assume that the URL and SAVE_AS matches). It would also solve issues I'm having in my custom theme (I just hard coded the paths there for now).

The pelican documentation contradicts itself a bit though: 

> DIRECT_TEMPLATES work a bit differently than noted above. Only the _SAVE_AS settings are available, but it is available for any direct template. (https://docs.getpelican.com/en/stable/settings.html#url-settings)

and 

> URLs for direct template pages are theme-dependent. Some themes use corresponding *_URL setting as string, while others hard-code them: 'archives.html', 'authors.html', 'categories.html', 'tags.html'. (same page)

I admit I had only read the former one. Might be worth opening a bug to pelican documentation to ask them to clarify this.
