### ISSUE TITLE
DIRECT_TEMPLATES: display real URL not file path

### ISSUE THREAD

**Issue by dArignac** [dArignac/pelican-extended-sitemap#15]
Currently the sitemap for example says `/tags.html` for the URL of tags, but the URL on the server could be `/tags/`.
Need to find a way to get the real path for the `DIRECT_TEMPLATE` choices.

The docs say:

> URLs for direct template pages are theme-dependent. Some themes use corresponding *_URL setting as string, while others hard-code them: 'archives.html', 'authors.html', 'categories.html', 'tags.html'.

Source: http://docs.getpelican.com/en/stable/settings.html

So we could rely on `*_URL` settings if available.

**Comment by VorpalBlade** [comment]
That solution sounds pretty good. See also https://github.com/dArignac/pelican-extended-sitemap/issues/14#issuecomment-488292218

**Comment by dArignac** [comment]
Fixed in 1.2.2, see https://pypi.org/project/pelican-extended-sitemap/1.2.2/
