### ISSUE TITLE
Problem with generation of sitemap without articles

### ISSUE THREAD

**Issue by jakub-olczyk** [dArignac/pelican-extended-sitemap#5]
Hello @dArignac! 

There seems to be a problem with generation of sitemap when there are only pages and no articles.

I don't know if this is a buggy behavior from plug-in perspective but it certainly is buggy from user perspective. 

I made simple example site for demonstrating this buggy behavior. It is included below

[bug-example-site.zip](https://github.com/dArignac/pelican-extended-sitemap/files/572033/bug-example-site.zip)

Cheers!

**Comment by dArignac** [comment]
Hi Jakub, I'll have a look into this.

**Comment by dArignac** [comment]
Hi Jakub,

I fixed the issue, thanks for the report!
The fix can be found in version 1.0.3:

https://github.com/dArignac/pelican-extended-sitemap/releases/tag/v1.0.3
https://pypi.python.org/pypi/pelican-extended-sitemap
